# FreemanAPI by Chloe @gaycoderprincess
# enjoy, nya~ :3

[main]
enabled=true
hl2=false
longjump=false
autohop=true
abh=false
abh_mixed=false
bhop_cap=false
better_maxvelocity=false
noclip_toggle=false

[advanced]
physics_steps=4
collision_density=2

[hl1]
cl_bob=0.01
cl_bobcycle=0.8
cl_bobup=0.5
cl_forwardspeed=400
cl_sidespeed=400
cl_upspeed=320
cl_movespeedkey=0.3
sv_gravity=800
sv_stopspeed=100
sv_maxspeed=320
sv_noclipspeed=320
sv_accelerate=10
sv_airaccelerate=10
sv_wateraccelerate=10
sv_friction=4
sv_edgefriction=2
sv_waterfriction=1
#sv_entgravity=1.0
sv_bounce=1.0
sv_stepsize=18
sv_maxvelocity=2000
#mp_footsteps=true
sv_rollangle=2
sv_rollspeed=200

[hl2]
cl_bob=0.002
cl_bobcycle=0.8
cl_bobup=0.5
cl_forwardspeed=450
cl_sidespeed=450
cl_upspeed=320
sv_gravity=600
sv_stopspeed=100
sv_maxspeed=320
sv_noclipaccelerate=5
sv_noclipspeed=5
sv_accelerate=10
sv_airaccelerate=10
sv_wateraccelerate=10
sv_friction=4
sv_edgefriction=2
sv_waterfriction=1
#sv_entgravity=1.0
sv_bounce=1.0
sv_stepsize=18
sv_maxvelocity=3500
#mp_footsteps=true
sv_rollangle=0
sv_rollspeed=200
#HL2_WALK_SPEED=150
HL2_NORM_SPEED=190
HL2_SPRINT_SPEED=320
GAMEMOVEMENT_JUMP_HEIGHT=21